# Generated by Django 3.0.2 on 2020-06-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_1', models.IntegerField(default=0)),
                ('attribute_2', models.IntegerField(default=0)),
                ('attribute_3', models.IntegerField(default=0)),
            ],
        ),
    ]
